/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.greenter_core.model;

import com.google.gson.annotations.SerializedName;

public class Address {
  
  @SerializedName("ubigueo")
  private String ubigueo = null;
  @SerializedName("codigoPais")
  private String codigoPais = null;
  @SerializedName("departamento")
  private String departamento = null;
  @SerializedName("provincia")
  private String provincia = null;
  @SerializedName("distrito")
  private String distrito = null;
  @SerializedName("urbanizacion")
  private String urbanizacion = null;
  @SerializedName("direccion")
  private String direccion = null;

  /**
   **/
  public String getUbigueo() {
    return ubigueo;
  }
  public void setUbigueo(String ubigueo) {
    this.ubigueo = ubigueo;
  }

  /**
   **/
  public String getCodigoPais() {
    return codigoPais;
  }
  public void setCodigoPais(String codigoPais) {
    this.codigoPais = codigoPais;
  }

  /**
   **/
  public String getDepartamento() {
    return departamento;
  }
  public void setDepartamento(String departamento) {
    this.departamento = departamento;
  }

  /**
   **/
  public String getProvincia() {
    return provincia;
  }
  public void setProvincia(String provincia) {
    this.provincia = provincia;
  }

  /**
   **/
  public String getDistrito() {
    return distrito;
  }
  public void setDistrito(String distrito) {
    this.distrito = distrito;
  }

  /**
   **/
  public String getUrbanizacion() {
    return urbanizacion;
  }
  public void setUrbanizacion(String urbanizacion) {
    this.urbanizacion = urbanizacion;
  }

  /**
   **/
  public String getDireccion() {
    return direccion;
  }
  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Address address = (Address) o;
    return (this.ubigueo == null ? address.ubigueo == null : this.ubigueo.equals(address.ubigueo)) &&
        (this.codigoPais == null ? address.codigoPais == null : this.codigoPais.equals(address.codigoPais)) &&
        (this.departamento == null ? address.departamento == null : this.departamento.equals(address.departamento)) &&
        (this.provincia == null ? address.provincia == null : this.provincia.equals(address.provincia)) &&
        (this.distrito == null ? address.distrito == null : this.distrito.equals(address.distrito)) &&
        (this.urbanizacion == null ? address.urbanizacion == null : this.urbanizacion.equals(address.urbanizacion)) &&
        (this.direccion == null ? address.direccion == null : this.direccion.equals(address.direccion));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ubigueo == null ? 0: this.ubigueo.hashCode());
    result = 31 * result + (this.codigoPais == null ? 0: this.codigoPais.hashCode());
    result = 31 * result + (this.departamento == null ? 0: this.departamento.hashCode());
    result = 31 * result + (this.provincia == null ? 0: this.provincia.hashCode());
    result = 31 * result + (this.distrito == null ? 0: this.distrito.hashCode());
    result = 31 * result + (this.urbanizacion == null ? 0: this.urbanizacion.hashCode());
    result = 31 * result + (this.direccion == null ? 0: this.direccion.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Address {\n");
    
    sb.append("  ubigueo: ").append(ubigueo).append("\n");
    sb.append("  codigoPais: ").append(codigoPais).append("\n");
    sb.append("  departamento: ").append(departamento).append("\n");
    sb.append("  provincia: ").append(provincia).append("\n");
    sb.append("  distrito: ").append(distrito).append("\n");
    sb.append("  urbanizacion: ").append(urbanizacion).append("\n");
    sb.append("  direccion: ").append(direccion).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
