/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.greenter_core.model;

import com.google.gson.annotations.SerializedName;

public class Document {
  
  @SerializedName("tipoDoc")
  private String tipoDoc = null;
  @SerializedName("nroDoc")
  private String nroDoc = null;

  /**
   **/
  
  public String getTipoDoc() {
    return tipoDoc;
  }
  public void setTipoDoc(String tipoDoc) {
    this.tipoDoc = tipoDoc;
  }

  /**
   **/
  
  public String getNroDoc() {
    return nroDoc;
  }
  public void setNroDoc(String nroDoc) {
    this.nroDoc = nroDoc;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Document document = (Document) o;
    return (this.tipoDoc == null ? document.tipoDoc == null : this.tipoDoc.equals(document.tipoDoc)) &&
        (this.nroDoc == null ? document.nroDoc == null : this.nroDoc.equals(document.nroDoc));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tipoDoc == null ? 0: this.tipoDoc.hashCode());
    result = 31 * result + (this.nroDoc == null ? 0: this.nroDoc.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("  tipoDoc: ").append(tipoDoc).append("\n");
    sb.append("  nroDoc: ").append(nroDoc).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
