/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.example.greenter_core.model;

import com.google.gson.annotations.SerializedName;

public class SaleDetail {
  
  @SerializedName("codUnidadMedida")
  private String codUnidadMedida = null;
  @SerializedName("ctdUnidadItem")
  private Float ctdUnidadItem = null;
  @SerializedName("codProducto")
  private String codProducto = null;
  @SerializedName("desItem")
  private String desItem = null;
  @SerializedName("mtoValorUnitario")
  private Float mtoValorUnitario = null;
  @SerializedName("mtoDsctoItem")
  private Float mtoDsctoItem = null;
  @SerializedName("mtoIgvItem")
  private Float mtoIgvItem = null;
  @SerializedName("tipAfeIgv")
  private String tipAfeIgv = null;
  @SerializedName("mtoIscItem")
  private Float mtoIscItem = null;
  @SerializedName("tipSisIsc")
  private String tipSisIsc = null;
  @SerializedName("mtoPrecioUnitario")
  private Float mtoPrecioUnitario = null;
  @SerializedName("mtoValorVenta")
  private Float mtoValorVenta = null;
  @SerializedName("mtoValorGratuito")
  private Float mtoValorGratuito = null;

  /**
   **/
  
  public String getCodUnidadMedida() {
    return codUnidadMedida;
  }
  public void setCodUnidadMedida(String codUnidadMedida) {
    this.codUnidadMedida = codUnidadMedida;
  }

  /**
   **/
  
  public Float getCtdUnidadItem() {
    return ctdUnidadItem;
  }
  public void setCtdUnidadItem(Float ctdUnidadItem) {
    this.ctdUnidadItem = ctdUnidadItem;
  }

  /**
   **/
  
  public String getCodProducto() {
    return codProducto;
  }
  public void setCodProducto(String codProducto) {
    this.codProducto = codProducto;
  }

  /**
   **/
  
  public String getDesItem() {
    return desItem;
  }
  public void setDesItem(String desItem) {
    this.desItem = desItem;
  }

  /**
   **/
  
  public Float getMtoValorUnitario() {
    return mtoValorUnitario;
  }
  public void setMtoValorUnitario(Float mtoValorUnitario) {
    this.mtoValorUnitario = mtoValorUnitario;
  }

  /**
   **/
  
  public Float getMtoDsctoItem() {
    return mtoDsctoItem;
  }
  public void setMtoDsctoItem(Float mtoDsctoItem) {
    this.mtoDsctoItem = mtoDsctoItem;
  }

  /**
   **/
  
  public Float getMtoIgvItem() {
    return mtoIgvItem;
  }
  public void setMtoIgvItem(Float mtoIgvItem) {
    this.mtoIgvItem = mtoIgvItem;
  }

  /**
   **/
  
  public String getTipAfeIgv() {
    return tipAfeIgv;
  }
  public void setTipAfeIgv(String tipAfeIgv) {
    this.tipAfeIgv = tipAfeIgv;
  }

  /**
   **/
  
  public Float getMtoIscItem() {
    return mtoIscItem;
  }
  public void setMtoIscItem(Float mtoIscItem) {
    this.mtoIscItem = mtoIscItem;
  }

  /**
   **/
  
  public String getTipSisIsc() {
    return tipSisIsc;
  }
  public void setTipSisIsc(String tipSisIsc) {
    this.tipSisIsc = tipSisIsc;
  }

  /**
   **/
  
  public Float getMtoPrecioUnitario() {
    return mtoPrecioUnitario;
  }
  public void setMtoPrecioUnitario(Float mtoPrecioUnitario) {
    this.mtoPrecioUnitario = mtoPrecioUnitario;
  }

  /**
   **/
  
  public Float getMtoValorVenta() {
    return mtoValorVenta;
  }
  public void setMtoValorVenta(Float mtoValorVenta) {
    this.mtoValorVenta = mtoValorVenta;
  }

  /**
   **/
  
  public Float getMtoValorGratuito() {
    return mtoValorGratuito;
  }
  public void setMtoValorGratuito(Float mtoValorGratuito) {
    this.mtoValorGratuito = mtoValorGratuito;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SaleDetail saleDetail = (SaleDetail) o;
    return (this.codUnidadMedida == null ? saleDetail.codUnidadMedida == null : this.codUnidadMedida.equals(saleDetail.codUnidadMedida)) &&
        (this.ctdUnidadItem == null ? saleDetail.ctdUnidadItem == null : this.ctdUnidadItem.equals(saleDetail.ctdUnidadItem)) &&
        (this.codProducto == null ? saleDetail.codProducto == null : this.codProducto.equals(saleDetail.codProducto)) &&
        (this.desItem == null ? saleDetail.desItem == null : this.desItem.equals(saleDetail.desItem)) &&
        (this.mtoValorUnitario == null ? saleDetail.mtoValorUnitario == null : this.mtoValorUnitario.equals(saleDetail.mtoValorUnitario)) &&
        (this.mtoDsctoItem == null ? saleDetail.mtoDsctoItem == null : this.mtoDsctoItem.equals(saleDetail.mtoDsctoItem)) &&
        (this.mtoIgvItem == null ? saleDetail.mtoIgvItem == null : this.mtoIgvItem.equals(saleDetail.mtoIgvItem)) &&
        (this.tipAfeIgv == null ? saleDetail.tipAfeIgv == null : this.tipAfeIgv.equals(saleDetail.tipAfeIgv)) &&
        (this.mtoIscItem == null ? saleDetail.mtoIscItem == null : this.mtoIscItem.equals(saleDetail.mtoIscItem)) &&
        (this.tipSisIsc == null ? saleDetail.tipSisIsc == null : this.tipSisIsc.equals(saleDetail.tipSisIsc)) &&
        (this.mtoPrecioUnitario == null ? saleDetail.mtoPrecioUnitario == null : this.mtoPrecioUnitario.equals(saleDetail.mtoPrecioUnitario)) &&
        (this.mtoValorVenta == null ? saleDetail.mtoValorVenta == null : this.mtoValorVenta.equals(saleDetail.mtoValorVenta)) &&
        (this.mtoValorGratuito == null ? saleDetail.mtoValorGratuito == null : this.mtoValorGratuito.equals(saleDetail.mtoValorGratuito));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.codUnidadMedida == null ? 0: this.codUnidadMedida.hashCode());
    result = 31 * result + (this.ctdUnidadItem == null ? 0: this.ctdUnidadItem.hashCode());
    result = 31 * result + (this.codProducto == null ? 0: this.codProducto.hashCode());
    result = 31 * result + (this.desItem == null ? 0: this.desItem.hashCode());
    result = 31 * result + (this.mtoValorUnitario == null ? 0: this.mtoValorUnitario.hashCode());
    result = 31 * result + (this.mtoDsctoItem == null ? 0: this.mtoDsctoItem.hashCode());
    result = 31 * result + (this.mtoIgvItem == null ? 0: this.mtoIgvItem.hashCode());
    result = 31 * result + (this.tipAfeIgv == null ? 0: this.tipAfeIgv.hashCode());
    result = 31 * result + (this.mtoIscItem == null ? 0: this.mtoIscItem.hashCode());
    result = 31 * result + (this.tipSisIsc == null ? 0: this.tipSisIsc.hashCode());
    result = 31 * result + (this.mtoPrecioUnitario == null ? 0: this.mtoPrecioUnitario.hashCode());
    result = 31 * result + (this.mtoValorVenta == null ? 0: this.mtoValorVenta.hashCode());
    result = 31 * result + (this.mtoValorGratuito == null ? 0: this.mtoValorGratuito.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SaleDetail {\n");
    
    sb.append("  codUnidadMedida: ").append(codUnidadMedida).append("\n");
    sb.append("  ctdUnidadItem: ").append(ctdUnidadItem).append("\n");
    sb.append("  codProducto: ").append(codProducto).append("\n");
    sb.append("  desItem: ").append(desItem).append("\n");
    sb.append("  mtoValorUnitario: ").append(mtoValorUnitario).append("\n");
    sb.append("  mtoDsctoItem: ").append(mtoDsctoItem).append("\n");
    sb.append("  mtoIgvItem: ").append(mtoIgvItem).append("\n");
    sb.append("  tipAfeIgv: ").append(tipAfeIgv).append("\n");
    sb.append("  mtoIscItem: ").append(mtoIscItem).append("\n");
    sb.append("  tipSisIsc: ").append(tipSisIsc).append("\n");
    sb.append("  mtoPrecioUnitario: ").append(mtoPrecioUnitario).append("\n");
    sb.append("  mtoValorVenta: ").append(mtoValorVenta).append("\n");
    sb.append("  mtoValorGratuito: ").append(mtoValorGratuito).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
