/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.analycer.greenter.client.model;

import com.google.gson.annotations.SerializedName;


public class Company {
  
  @SerializedName("ruc")
  private String ruc = null;
  @SerializedName("razonSocial")
  private String razonSocial = null;
  @SerializedName("nombreComercial")
  private String nombreComercial = null;
  @SerializedName("address")
  private Address address = null;

  /**
   **/
  
  public String getRuc() {
    return ruc;
  }
  public void setRuc(String ruc) {
    this.ruc = ruc;
  }

  /**
   **/
  
  public String getRazonSocial() {
    return razonSocial;
  }
  public void setRazonSocial(String razonSocial) {
    this.razonSocial = razonSocial;
  }

  /**
   **/
  
  public String getNombreComercial() {
    return nombreComercial;
  }
  public void setNombreComercial(String nombreComercial) {
    this.nombreComercial = nombreComercial;
  }

  /**
   **/
  
  public Address getAddress() {
    return address;
  }
  public void setAddress(Address address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Company company = (Company) o;
    return (this.ruc == null ? company.ruc == null : this.ruc.equals(company.ruc)) &&
        (this.razonSocial == null ? company.razonSocial == null : this.razonSocial.equals(company.razonSocial)) &&
        (this.nombreComercial == null ? company.nombreComercial == null : this.nombreComercial.equals(company.nombreComercial)) &&
        (this.address == null ? company.address == null : this.address.equals(company.address));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ruc == null ? 0: this.ruc.hashCode());
    result = 31 * result + (this.razonSocial == null ? 0: this.razonSocial.hashCode());
    result = 31 * result + (this.nombreComercial == null ? 0: this.nombreComercial.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Company {\n");
    
    sb.append("  ruc: ").append(ruc).append("\n");
    sb.append("  razonSocial: ").append(razonSocial).append("\n");
    sb.append("  nombreComercial: ").append(nombreComercial).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
