/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.analycer.greenter.client.model;

import java.util.*;
import java.util.Date;
import com.google.gson.annotations.SerializedName;

public class Invoice {
  
  @SerializedName("tipoDoc")
  private String tipoDoc = null;
  @SerializedName("serie")
  private String serie = null;
  @SerializedName("correlativo")
  private String correlativo = null;
  @SerializedName("fechaEmision")
  private Date fechaEmision = null;
  @SerializedName("client")
  private Client client = null;
  @SerializedName("company")
  private Company company = null;
  @SerializedName("tipoMoneda")
  private String tipoMoneda = null;
  @SerializedName("sumOtrosCargos")
  private Float sumOtrosCargos = null;
  @SerializedName("mtoOperGravadas")
  private Float mtoOperGravadas = null;
  @SerializedName("mtoOperInafectas")
  private Float mtoOperInafectas = null;
  @SerializedName("mtoOperExoneradas")
  private Float mtoOperExoneradas = null;
  @SerializedName("mtoIGV")
  private Float mtoIGV = null;
  @SerializedName("mtoISC")
  private Float mtoISC = null;
  @SerializedName("mtoOtrosTributos")
  private Float mtoOtrosTributos = null;
  @SerializedName("mtoImpVenta")
  private Float mtoImpVenta = null;
  @SerializedName("details")
  private List<SaleDetail> details = null;
  @SerializedName("legends")
  private List<Legend> legends = null;
  @SerializedName("relDocs")
  private List<Document> relDocs = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("tipoOperacion")
  private String tipoOperacion = null;
  @SerializedName("sumDsctoGlobal")
  private Float sumDsctoGlobal = null;
  @SerializedName("mtoDescuentos")
  private Float mtoDescuentos = null;
  @SerializedName("mtoOperGratuitas")
  private Float mtoOperGratuitas = null;
  @SerializedName("totalAnticipos")
  private Float totalAnticipos = null;
  @SerializedName("perception")
  private SalePerception perception = null;
  @SerializedName("compra")
  private String compra = null;
  @SerializedName("guias")
  private List<Document> guias = null;
  @SerializedName("anticipos")
  private List<Prepayment> anticipos = null;
  @SerializedName("detraccion")
  private Detraction detraccion = null;
  @SerializedName("guiaEmbebida")
  private EmbededDespatch guiaEmbebida = null;

  /**
   **/
  
  public String getTipoDoc() {
    return tipoDoc;
  }
  public void setTipoDoc(String tipoDoc) {
    this.tipoDoc = tipoDoc;
  }

  /**
   **/
  
  public String getSerie() {
    return serie;
  }
  public void setSerie(String serie) {
    this.serie = serie;
  }

  /**
   **/
  
  public String getCorrelativo() {
    return correlativo;
  }
  public void setCorrelativo(String correlativo) {
    this.correlativo = correlativo;
  }

  /**
   **/
  
  public Date getFechaEmision() {
    return fechaEmision;
  }
  public void setFechaEmision(Date fechaEmision) {
    this.fechaEmision = fechaEmision;
  }

  /**
   **/
  
  public Client getClient() {
    return client;
  }
  public void setClient(Client client) {
    this.client = client;
  }

  /**
   **/
  
  public Company getCompany() {
    return company;
  }
  public void setCompany(Company company) {
    this.company = company;
  }

  /**
   **/
  
  public String getTipoMoneda() {
    return tipoMoneda;
  }
  public void setTipoMoneda(String tipoMoneda) {
    this.tipoMoneda = tipoMoneda;
  }

  /**
   **/
  
  public Float getSumOtrosCargos() {
    return sumOtrosCargos;
  }
  public void setSumOtrosCargos(Float sumOtrosCargos) {
    this.sumOtrosCargos = sumOtrosCargos;
  }

  /**
   **/
  
  public Float getMtoOperGravadas() {
    return mtoOperGravadas;
  }
  public void setMtoOperGravadas(Float mtoOperGravadas) {
    this.mtoOperGravadas = mtoOperGravadas;
  }

  /**
   **/
  
  public Float getMtoOperInafectas() {
    return mtoOperInafectas;
  }
  public void setMtoOperInafectas(Float mtoOperInafectas) {
    this.mtoOperInafectas = mtoOperInafectas;
  }

  /**
   **/
  
  public Float getMtoOperExoneradas() {
    return mtoOperExoneradas;
  }
  public void setMtoOperExoneradas(Float mtoOperExoneradas) {
    this.mtoOperExoneradas = mtoOperExoneradas;
  }

  /**
   **/
  
  public Float getMtoIGV() {
    return mtoIGV;
  }
  public void setMtoIGV(Float mtoIGV) {
    this.mtoIGV = mtoIGV;
  }

  /**
   **/
  
  public Float getMtoISC() {
    return mtoISC;
  }
  public void setMtoISC(Float mtoISC) {
    this.mtoISC = mtoISC;
  }

  /**
   **/
  
  public Float getMtoOtrosTributos() {
    return mtoOtrosTributos;
  }
  public void setMtoOtrosTributos(Float mtoOtrosTributos) {
    this.mtoOtrosTributos = mtoOtrosTributos;
  }

  /**
   **/
  
  public Float getMtoImpVenta() {
    return mtoImpVenta;
  }
  public void setMtoImpVenta(Float mtoImpVenta) {
    this.mtoImpVenta = mtoImpVenta;
  }

  /**
   **/
  
  public List<SaleDetail> getDetails() {
    return details;
  }
  public void setDetails(List<SaleDetail> details) {
    this.details = details;
  }

  /**
   **/
  
  public List<Legend> getLegends() {
    return legends;
  }
  public void setLegends(List<Legend> legends) {
    this.legends = legends;
  }

  /**
   **/
  
  public List<Document> getRelDocs() {
    return relDocs;
  }
  public void setRelDocs(List<Document> relDocs) {
    this.relDocs = relDocs;
  }

  /**
   **/
  
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  
  public String getTipoOperacion() {
    return tipoOperacion;
  }
  public void setTipoOperacion(String tipoOperacion) {
    this.tipoOperacion = tipoOperacion;
  }

  /**
   **/
  
  public Float getSumDsctoGlobal() {
    return sumDsctoGlobal;
  }
  public void setSumDsctoGlobal(Float sumDsctoGlobal) {
    this.sumDsctoGlobal = sumDsctoGlobal;
  }

  /**
   **/
  
  public Float getMtoDescuentos() {
    return mtoDescuentos;
  }
  public void setMtoDescuentos(Float mtoDescuentos) {
    this.mtoDescuentos = mtoDescuentos;
  }

  /**
   **/
  
  public Float getMtoOperGratuitas() {
    return mtoOperGratuitas;
  }
  public void setMtoOperGratuitas(Float mtoOperGratuitas) {
    this.mtoOperGratuitas = mtoOperGratuitas;
  }

  /**
   **/
  
  public Float getTotalAnticipos() {
    return totalAnticipos;
  }
  public void setTotalAnticipos(Float totalAnticipos) {
    this.totalAnticipos = totalAnticipos;
  }

  /**
   **/
  
  public SalePerception getPerception() {
    return perception;
  }
  public void setPerception(SalePerception perception) {
    this.perception = perception;
  }

  /**
   **/
  
  public String getCompra() {
    return compra;
  }
  public void setCompra(String compra) {
    this.compra = compra;
  }

  /**
   **/
  
  public List<Document> getGuias() {
    return guias;
  }
  public void setGuias(List<Document> guias) {
    this.guias = guias;
  }

  /**
   **/
  
  public List<Prepayment> getAnticipos() {
    return anticipos;
  }
  public void setAnticipos(List<Prepayment> anticipos) {
    this.anticipos = anticipos;
  }

  /**
   **/
  
  public Detraction getDetraccion() {
    return detraccion;
  }
  public void setDetraccion(Detraction detraccion) {
    this.detraccion = detraccion;
  }

  /**
   **/
  
  public EmbededDespatch getGuiaEmbebida() {
    return guiaEmbebida;
  }
  public void setGuiaEmbebida(EmbededDespatch guiaEmbebida) {
    this.guiaEmbebida = guiaEmbebida;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Invoice invoice = (Invoice) o;
    return (this.tipoDoc == null ? invoice.tipoDoc == null : this.tipoDoc.equals(invoice.tipoDoc)) &&
        (this.serie == null ? invoice.serie == null : this.serie.equals(invoice.serie)) &&
        (this.correlativo == null ? invoice.correlativo == null : this.correlativo.equals(invoice.correlativo)) &&
        (this.fechaEmision == null ? invoice.fechaEmision == null : this.fechaEmision.equals(invoice.fechaEmision)) &&
        (this.client == null ? invoice.client == null : this.client.equals(invoice.client)) &&
        (this.company == null ? invoice.company == null : this.company.equals(invoice.company)) &&
        (this.tipoMoneda == null ? invoice.tipoMoneda == null : this.tipoMoneda.equals(invoice.tipoMoneda)) &&
        (this.sumOtrosCargos == null ? invoice.sumOtrosCargos == null : this.sumOtrosCargos.equals(invoice.sumOtrosCargos)) &&
        (this.mtoOperGravadas == null ? invoice.mtoOperGravadas == null : this.mtoOperGravadas.equals(invoice.mtoOperGravadas)) &&
        (this.mtoOperInafectas == null ? invoice.mtoOperInafectas == null : this.mtoOperInafectas.equals(invoice.mtoOperInafectas)) &&
        (this.mtoOperExoneradas == null ? invoice.mtoOperExoneradas == null : this.mtoOperExoneradas.equals(invoice.mtoOperExoneradas)) &&
        (this.mtoIGV == null ? invoice.mtoIGV == null : this.mtoIGV.equals(invoice.mtoIGV)) &&
        (this.mtoISC == null ? invoice.mtoISC == null : this.mtoISC.equals(invoice.mtoISC)) &&
        (this.mtoOtrosTributos == null ? invoice.mtoOtrosTributos == null : this.mtoOtrosTributos.equals(invoice.mtoOtrosTributos)) &&
        (this.mtoImpVenta == null ? invoice.mtoImpVenta == null : this.mtoImpVenta.equals(invoice.mtoImpVenta)) &&
        (this.details == null ? invoice.details == null : this.details.equals(invoice.details)) &&
        (this.legends == null ? invoice.legends == null : this.legends.equals(invoice.legends)) &&
        (this.relDocs == null ? invoice.relDocs == null : this.relDocs.equals(invoice.relDocs)) &&
        (this.name == null ? invoice.name == null : this.name.equals(invoice.name)) &&
        (this.tipoOperacion == null ? invoice.tipoOperacion == null : this.tipoOperacion.equals(invoice.tipoOperacion)) &&
        (this.sumDsctoGlobal == null ? invoice.sumDsctoGlobal == null : this.sumDsctoGlobal.equals(invoice.sumDsctoGlobal)) &&
        (this.mtoDescuentos == null ? invoice.mtoDescuentos == null : this.mtoDescuentos.equals(invoice.mtoDescuentos)) &&
        (this.mtoOperGratuitas == null ? invoice.mtoOperGratuitas == null : this.mtoOperGratuitas.equals(invoice.mtoOperGratuitas)) &&
        (this.totalAnticipos == null ? invoice.totalAnticipos == null : this.totalAnticipos.equals(invoice.totalAnticipos)) &&
        (this.perception == null ? invoice.perception == null : this.perception.equals(invoice.perception)) &&
        (this.compra == null ? invoice.compra == null : this.compra.equals(invoice.compra)) &&
        (this.guias == null ? invoice.guias == null : this.guias.equals(invoice.guias)) &&
        (this.anticipos == null ? invoice.anticipos == null : this.anticipos.equals(invoice.anticipos)) &&
        (this.detraccion == null ? invoice.detraccion == null : this.detraccion.equals(invoice.detraccion)) &&
        (this.guiaEmbebida == null ? invoice.guiaEmbebida == null : this.guiaEmbebida.equals(invoice.guiaEmbebida));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tipoDoc == null ? 0: this.tipoDoc.hashCode());
    result = 31 * result + (this.serie == null ? 0: this.serie.hashCode());
    result = 31 * result + (this.correlativo == null ? 0: this.correlativo.hashCode());
    result = 31 * result + (this.fechaEmision == null ? 0: this.fechaEmision.hashCode());
    result = 31 * result + (this.client == null ? 0: this.client.hashCode());
    result = 31 * result + (this.company == null ? 0: this.company.hashCode());
    result = 31 * result + (this.tipoMoneda == null ? 0: this.tipoMoneda.hashCode());
    result = 31 * result + (this.sumOtrosCargos == null ? 0: this.sumOtrosCargos.hashCode());
    result = 31 * result + (this.mtoOperGravadas == null ? 0: this.mtoOperGravadas.hashCode());
    result = 31 * result + (this.mtoOperInafectas == null ? 0: this.mtoOperInafectas.hashCode());
    result = 31 * result + (this.mtoOperExoneradas == null ? 0: this.mtoOperExoneradas.hashCode());
    result = 31 * result + (this.mtoIGV == null ? 0: this.mtoIGV.hashCode());
    result = 31 * result + (this.mtoISC == null ? 0: this.mtoISC.hashCode());
    result = 31 * result + (this.mtoOtrosTributos == null ? 0: this.mtoOtrosTributos.hashCode());
    result = 31 * result + (this.mtoImpVenta == null ? 0: this.mtoImpVenta.hashCode());
    result = 31 * result + (this.details == null ? 0: this.details.hashCode());
    result = 31 * result + (this.legends == null ? 0: this.legends.hashCode());
    result = 31 * result + (this.relDocs == null ? 0: this.relDocs.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.tipoOperacion == null ? 0: this.tipoOperacion.hashCode());
    result = 31 * result + (this.sumDsctoGlobal == null ? 0: this.sumDsctoGlobal.hashCode());
    result = 31 * result + (this.mtoDescuentos == null ? 0: this.mtoDescuentos.hashCode());
    result = 31 * result + (this.mtoOperGratuitas == null ? 0: this.mtoOperGratuitas.hashCode());
    result = 31 * result + (this.totalAnticipos == null ? 0: this.totalAnticipos.hashCode());
    result = 31 * result + (this.perception == null ? 0: this.perception.hashCode());
    result = 31 * result + (this.compra == null ? 0: this.compra.hashCode());
    result = 31 * result + (this.guias == null ? 0: this.guias.hashCode());
    result = 31 * result + (this.anticipos == null ? 0: this.anticipos.hashCode());
    result = 31 * result + (this.detraccion == null ? 0: this.detraccion.hashCode());
    result = 31 * result + (this.guiaEmbebida == null ? 0: this.guiaEmbebida.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Invoice {\n");
    
    sb.append("  tipoDoc: ").append(tipoDoc).append("\n");
    sb.append("  serie: ").append(serie).append("\n");
    sb.append("  correlativo: ").append(correlativo).append("\n");
    sb.append("  fechaEmision: ").append(fechaEmision).append("\n");
    sb.append("  client: ").append(client).append("\n");
    sb.append("  company: ").append(company).append("\n");
    sb.append("  tipoMoneda: ").append(tipoMoneda).append("\n");
    sb.append("  sumOtrosCargos: ").append(sumOtrosCargos).append("\n");
    sb.append("  mtoOperGravadas: ").append(mtoOperGravadas).append("\n");
    sb.append("  mtoOperInafectas: ").append(mtoOperInafectas).append("\n");
    sb.append("  mtoOperExoneradas: ").append(mtoOperExoneradas).append("\n");
    sb.append("  mtoIGV: ").append(mtoIGV).append("\n");
    sb.append("  mtoISC: ").append(mtoISC).append("\n");
    sb.append("  mtoOtrosTributos: ").append(mtoOtrosTributos).append("\n");
    sb.append("  mtoImpVenta: ").append(mtoImpVenta).append("\n");
    sb.append("  details: ").append(details).append("\n");
    sb.append("  legends: ").append(legends).append("\n");
    sb.append("  relDocs: ").append(relDocs).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  tipoOperacion: ").append(tipoOperacion).append("\n");
    sb.append("  sumDsctoGlobal: ").append(sumDsctoGlobal).append("\n");
    sb.append("  mtoDescuentos: ").append(mtoDescuentos).append("\n");
    sb.append("  mtoOperGratuitas: ").append(mtoOperGratuitas).append("\n");
    sb.append("  totalAnticipos: ").append(totalAnticipos).append("\n");
    sb.append("  perception: ").append(perception).append("\n");
    sb.append("  compra: ").append(compra).append("\n");
    sb.append("  guias: ").append(guias).append("\n");
    sb.append("  anticipos: ").append(anticipos).append("\n");
    sb.append("  detraccion: ").append(detraccion).append("\n");
    sb.append("  guiaEmbebida: ").append(guiaEmbebida).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
