/**
 * Grenter App
 * Aplicación para MYPEs empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenter.core.model;

import com.google.gson.annotations.SerializedName;

public class AuthResponse {
  
  @SerializedName("token")
  private String token = null;

  public String getToken() {
    return token;
  }
  public void setToken(String token) {
    this.token = token;
  }
}
