/**
 * Grenter App
 * Aplicacion para mypes empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenter.core.model;

import com.google.gson.annotations.SerializedName;

public class Prepayment {
  
  @SerializedName("tipoDocRel")
  private String tipoDocRel = null;
  @SerializedName("nroDocRel")
  private String nroDocRel = null;
  @SerializedName("total")
  private Float total = null;

  /**
   **/
  
  public String getTipoDocRel() {
    return tipoDocRel;
  }
  public void setTipoDocRel(String tipoDocRel) {
    this.tipoDocRel = tipoDocRel;
  }

  /**
   **/
  
  public String getNroDocRel() {
    return nroDocRel;
  }
  public void setNroDocRel(String nroDocRel) {
    this.nroDocRel = nroDocRel;
  }

  /**
   **/
  
  public Float getTotal() {
    return total;
  }
  public void setTotal(Float total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Prepayment prepayment = (Prepayment) o;
    return (this.tipoDocRel == null ? prepayment.tipoDocRel == null : this.tipoDocRel.equals(prepayment.tipoDocRel)) &&
        (this.nroDocRel == null ? prepayment.nroDocRel == null : this.nroDocRel.equals(prepayment.nroDocRel)) &&
        (this.total == null ? prepayment.total == null : this.total.equals(prepayment.total));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.tipoDocRel == null ? 0: this.tipoDocRel.hashCode());
    result = 31 * result + (this.nroDocRel == null ? 0: this.nroDocRel.hashCode());
    result = 31 * result + (this.total == null ? 0: this.total.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Prepayment {\n");
    
    sb.append("  tipoDocRel: ").append(tipoDocRel).append("\n");
    sb.append("  nroDocRel: ").append(nroDocRel).append("\n");
    sb.append("  total: ").append(total).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
