/**
 * Grenter App
 * Aplicación para MYPEs empleando sus comprobantes electrónicos
 *
 * OpenAPI spec version: 1.0.0
 * Contact: giansalex@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.greenter.core.model;

import java.util.*;
import com.google.gson.annotations.SerializedName;

public class RucResponse {
  
  @SerializedName("ruc")
  private String ruc = null;
  @SerializedName("razonSocial")
  private String razonSocial = null;
  @SerializedName("nombreComercial")
  private String nombreComercial = null;
  @SerializedName("telefonos")
  private List<String> telefonos = null;
  @SerializedName("tipo")
  private String tipo = null;
  @SerializedName("estado")
  private String estado = null;
  @SerializedName("condicion")
  private String condicion = null;
  @SerializedName("direccion")
  private String direccion = null;
  @SerializedName("fechaInscripcion")
  private String fechaInscripcion = null;
  @SerializedName("sistEmsion")
  private String sistEmsion = null;
  @SerializedName("sistContabilidad")
  private String sistContabilidad = null;
  @SerializedName("actExterior")
  private String actExterior = null;
  @SerializedName("actEconomicas")
  private List<String> actEconomicas = null;
  @SerializedName("cpPago")
  private List<String> cpPago = null;
  @SerializedName("sistElectronica")
  private List<String> sistElectronica = null;
  @SerializedName("fechaEmisorFe")
  private String fechaEmisorFe = null;
  @SerializedName("cpeElectronico")
  private List<String> cpeElectronico = null;
  @SerializedName("fechaPle")
  private String fechaPle = null;
  @SerializedName("padrones")
  private String padrones = null;

  /**
   **/
  
  public String getRuc() {
    return ruc;
  }
  public void setRuc(String ruc) {
    this.ruc = ruc;
  }

  /**
   **/
  
  public String getRazonSocial() {
    return razonSocial;
  }
  public void setRazonSocial(String razonSocial) {
    this.razonSocial = razonSocial;
  }

  /**
   **/
  
  public String getNombreComercial() {
    return nombreComercial;
  }
  public void setNombreComercial(String nombreComercial) {
    this.nombreComercial = nombreComercial;
  }

  /**
   **/
  
  public List<String> getTelefonos() {
    return telefonos;
  }
  public void setTelefonos(List<String> telefonos) {
    this.telefonos = telefonos;
  }

  /**
   **/
  
  public String getTipo() {
    return tipo;
  }
  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  /**
   **/
  
  public String getEstado() {
    return estado;
  }
  public void setEstado(String estado) {
    this.estado = estado;
  }

  /**
   **/
  
  public String getCondicion() {
    return condicion;
  }
  public void setCondicion(String condicion) {
    this.condicion = condicion;
  }

  /**
   **/
  
  public String getDireccion() {
    return direccion;
  }
  public void setDireccion(String direccion) {
    this.direccion = direccion;
  }

  /**
   **/
  
  public String getFechaInscripcion() {
    return fechaInscripcion;
  }
  public void setFechaInscripcion(String fechaInscripcion) {
    this.fechaInscripcion = fechaInscripcion;
  }

  /**
   **/
  
  public String getSistEmsion() {
    return sistEmsion;
  }
  public void setSistEmsion(String sistEmsion) {
    this.sistEmsion = sistEmsion;
  }

  /**
   **/
  
  public String getSistContabilidad() {
    return sistContabilidad;
  }
  public void setSistContabilidad(String sistContabilidad) {
    this.sistContabilidad = sistContabilidad;
  }

  /**
   **/
  
  public String getActExterior() {
    return actExterior;
  }
  public void setActExterior(String actExterior) {
    this.actExterior = actExterior;
  }

  /**
   **/
  
  public List<String> getActEconomicas() {
    return actEconomicas;
  }
  public void setActEconomicas(List<String> actEconomicas) {
    this.actEconomicas = actEconomicas;
  }

  /**
   **/
  
  public List<String> getCpPago() {
    return cpPago;
  }
  public void setCpPago(List<String> cpPago) {
    this.cpPago = cpPago;
  }

  /**
   **/
  
  public List<String> getSistElectronica() {
    return sistElectronica;
  }
  public void setSistElectronica(List<String> sistElectronica) {
    this.sistElectronica = sistElectronica;
  }

  /**
   **/
  
  public String getFechaEmisorFe() {
    return fechaEmisorFe;
  }
  public void setFechaEmisorFe(String fechaEmisorFe) {
    this.fechaEmisorFe = fechaEmisorFe;
  }

  /**
   **/
  
  public List<String> getCpeElectronico() {
    return cpeElectronico;
  }
  public void setCpeElectronico(List<String> cpeElectronico) {
    this.cpeElectronico = cpeElectronico;
  }

  /**
   **/
  
  public String getFechaPle() {
    return fechaPle;
  }
  public void setFechaPle(String fechaPle) {
    this.fechaPle = fechaPle;
  }

  /**
   **/
  
  public String getPadrones() {
    return padrones;
  }
  public void setPadrones(String padrones) {
    this.padrones = padrones;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RucResponse rucResponse = (RucResponse) o;
    return (this.ruc == null ? rucResponse.ruc == null : this.ruc.equals(rucResponse.ruc)) &&
        (this.razonSocial == null ? rucResponse.razonSocial == null : this.razonSocial.equals(rucResponse.razonSocial)) &&
        (this.nombreComercial == null ? rucResponse.nombreComercial == null : this.nombreComercial.equals(rucResponse.nombreComercial)) &&
        (this.telefonos == null ? rucResponse.telefonos == null : this.telefonos.equals(rucResponse.telefonos)) &&
        (this.tipo == null ? rucResponse.tipo == null : this.tipo.equals(rucResponse.tipo)) &&
        (this.estado == null ? rucResponse.estado == null : this.estado.equals(rucResponse.estado)) &&
        (this.condicion == null ? rucResponse.condicion == null : this.condicion.equals(rucResponse.condicion)) &&
        (this.direccion == null ? rucResponse.direccion == null : this.direccion.equals(rucResponse.direccion)) &&
        (this.fechaInscripcion == null ? rucResponse.fechaInscripcion == null : this.fechaInscripcion.equals(rucResponse.fechaInscripcion)) &&
        (this.sistEmsion == null ? rucResponse.sistEmsion == null : this.sistEmsion.equals(rucResponse.sistEmsion)) &&
        (this.sistContabilidad == null ? rucResponse.sistContabilidad == null : this.sistContabilidad.equals(rucResponse.sistContabilidad)) &&
        (this.actExterior == null ? rucResponse.actExterior == null : this.actExterior.equals(rucResponse.actExterior)) &&
        (this.actEconomicas == null ? rucResponse.actEconomicas == null : this.actEconomicas.equals(rucResponse.actEconomicas)) &&
        (this.cpPago == null ? rucResponse.cpPago == null : this.cpPago.equals(rucResponse.cpPago)) &&
        (this.sistElectronica == null ? rucResponse.sistElectronica == null : this.sistElectronica.equals(rucResponse.sistElectronica)) &&
        (this.fechaEmisorFe == null ? rucResponse.fechaEmisorFe == null : this.fechaEmisorFe.equals(rucResponse.fechaEmisorFe)) &&
        (this.cpeElectronico == null ? rucResponse.cpeElectronico == null : this.cpeElectronico.equals(rucResponse.cpeElectronico)) &&
        (this.fechaPle == null ? rucResponse.fechaPle == null : this.fechaPle.equals(rucResponse.fechaPle)) &&
        (this.padrones == null ? rucResponse.padrones == null : this.padrones.equals(rucResponse.padrones));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ruc == null ? 0: this.ruc.hashCode());
    result = 31 * result + (this.razonSocial == null ? 0: this.razonSocial.hashCode());
    result = 31 * result + (this.nombreComercial == null ? 0: this.nombreComercial.hashCode());
    result = 31 * result + (this.telefonos == null ? 0: this.telefonos.hashCode());
    result = 31 * result + (this.tipo == null ? 0: this.tipo.hashCode());
    result = 31 * result + (this.estado == null ? 0: this.estado.hashCode());
    result = 31 * result + (this.condicion == null ? 0: this.condicion.hashCode());
    result = 31 * result + (this.direccion == null ? 0: this.direccion.hashCode());
    result = 31 * result + (this.fechaInscripcion == null ? 0: this.fechaInscripcion.hashCode());
    result = 31 * result + (this.sistEmsion == null ? 0: this.sistEmsion.hashCode());
    result = 31 * result + (this.sistContabilidad == null ? 0: this.sistContabilidad.hashCode());
    result = 31 * result + (this.actExterior == null ? 0: this.actExterior.hashCode());
    result = 31 * result + (this.actEconomicas == null ? 0: this.actEconomicas.hashCode());
    result = 31 * result + (this.cpPago == null ? 0: this.cpPago.hashCode());
    result = 31 * result + (this.sistElectronica == null ? 0: this.sistElectronica.hashCode());
    result = 31 * result + (this.fechaEmisorFe == null ? 0: this.fechaEmisorFe.hashCode());
    result = 31 * result + (this.cpeElectronico == null ? 0: this.cpeElectronico.hashCode());
    result = 31 * result + (this.fechaPle == null ? 0: this.fechaPle.hashCode());
    result = 31 * result + (this.padrones == null ? 0: this.padrones.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RucResponse {\n");
    
    sb.append("  ruc: ").append(ruc).append("\n");
    sb.append("  razonSocial: ").append(razonSocial).append("\n");
    sb.append("  nombreComercial: ").append(nombreComercial).append("\n");
    sb.append("  telefonos: ").append(telefonos).append("\n");
    sb.append("  tipo: ").append(tipo).append("\n");
    sb.append("  estado: ").append(estado).append("\n");
    sb.append("  condicion: ").append(condicion).append("\n");
    sb.append("  direccion: ").append(direccion).append("\n");
    sb.append("  fechaInscripcion: ").append(fechaInscripcion).append("\n");
    sb.append("  sistEmsion: ").append(sistEmsion).append("\n");
    sb.append("  sistContabilidad: ").append(sistContabilidad).append("\n");
    sb.append("  actExterior: ").append(actExterior).append("\n");
    sb.append("  actEconomicas: ").append(actEconomicas).append("\n");
    sb.append("  cpPago: ").append(cpPago).append("\n");
    sb.append("  sistElectronica: ").append(sistElectronica).append("\n");
    sb.append("  fechaEmisorFe: ").append(fechaEmisorFe).append("\n");
    sb.append("  cpeElectronico: ").append(cpeElectronico).append("\n");
    sb.append("  fechaPle: ").append(fechaPle).append("\n");
    sb.append("  padrones: ").append(padrones).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
